#!/usr/bin/env python3
"""
Generate C++ theme headers from a Visage Theme Designer JSON file.

Usage:
    python3 scripts/generate_theme.py theme.json                    # Print Visage header to stdout
    python3 scripts/generate_theme.py theme.json --output Source/Theme.h
    python3 scripts/generate_theme.py theme.json --mode juce        # JUCE LookAndFeel class
    python3 scripts/generate_theme.py theme.json --mode both --output Source/Theme
    python3 scripts/generate_theme.py theme.json --validate-only
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path


def hex_alpha_to_argb(hex_color: str, alpha: float) -> int:
    """Convert '#RRGGBB' + alpha (0.0-1.0) to 0xAARRGGBB integer."""
    h = hex_color.lstrip("#")
    if len(h) == 8:
        # Already has alpha channel, use it
        return int(h, 16)
    if len(h) != 6:
        raise ValueError(f"Invalid hex color: {hex_color}")
    r = int(h[0:2], 16)
    g = int(h[2:4], 16)
    b = int(h[4:6], 16)
    a = round(max(0.0, min(1.0, alpha)) * 255)
    return (a << 24) | (r << 16) | (g << 8) | b


def format_argb(value: int) -> str:
    """Format as C++ hex literal: 0xAARRGGBB"""
    return f"0x{value & 0xFFFFFFFF:08X}"


def validate_token_name(name: str) -> bool:
    """Check if name is a valid C++ identifier."""
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name))


def load_theme(path: str) -> dict:
    """Load and validate a theme JSON file. Resolves base inheritance."""
    with open(path, "r") as f:
        theme = json.load(f)

    if not theme.get("meta"):
        raise ValueError("Theme JSON must have a 'meta' section")

    base_name = theme["meta"].get("base")
    if base_name:
        # Resolve base theme from same directory or presets/
        theme_dir = Path(path).parent
        base_path = theme_dir / f"{base_name}.json"
        if not base_path.exists():
            base_path = theme_dir / "presets" / f"{base_name}.json"
        if not base_path.exists():
            base_path = theme_dir / f"default.json"
        if not base_path.exists():
            raise FileNotFoundError(f"Base theme not found: {base_name}")

        base = load_theme(str(base_path))
        theme = merge_themes(base, theme)

    return theme


def merge_themes(base: dict, override: dict) -> dict:
    """Merge override theme onto base. Override values win."""
    import copy
    result = copy.deepcopy(base)
    for section in ("colors", "values", "custom", "juce"):
        if section in override and override[section]:
            result.setdefault(section, {}).update(override[section])
    result["meta"] = override["meta"]
    if "overrides" in override:
        result["overrides"] = override["overrides"]
    return result


def validate_theme(theme: dict) -> list:
    """Validate theme and return list of errors."""
    errors = []
    for section in ("colors", "custom"):
        for name, token in theme.get(section, {}).items():
            if not validate_token_name(name):
                errors.append(f"Invalid C++ identifier in {section}: '{name}'")
            if "value" not in token:
                errors.append(f"Missing 'value' in {section}.{name}")
            elif not re.match(r"^#[0-9A-Fa-f]{6,8}$", token["value"]):
                errors.append(f"Invalid hex color in {section}.{name}: '{token['value']}'")
    for name, token in theme.get("values", {}).items():
        if not validate_token_name(name):
            errors.append(f"Invalid C++ identifier in values: '{name}'")
        if "value" not in token:
            errors.append(f"Missing 'value' in values.{name}")
        elif not isinstance(token["value"], (int, float)):
            errors.append(f"Value must be numeric in values.{name}: '{token['value']}'")
    return errors


def generate_visage_header(theme: dict, source_path: str = "") -> str:
    """Generate a C++ header with VISAGE_THEME_COLOR/VALUE declarations."""
    meta = theme["meta"]
    ns = re.sub(r"[^a-z0-9_]", "_", meta["name"].lower()).strip("_")

    lines = [
        "#pragma once",
        f"// Generated by Visage Theme Designer",
        f"// Theme: {meta['name']} v{meta.get('version', '1.0.0')}",
        f"// Source: {source_path}" if source_path else "",
        f"// Generated: {datetime.now().isoformat()}",
        "// DO NOT EDIT - regenerate from theme JSON",
        "",
        '#include "visage_graphics/theme.h"',
        "",
        f"namespace {ns} {{",
        "",
    ]

    # Standard Visage colors
    if theme.get("colors"):
        lines.append("// Visage Widget Colors")
        prev_group = ""
        for name, token in theme["colors"].items():
            # Group by prefix (UiButton, TextButton, Toggle, etc.)
            group = re.match(r"^[A-Z][a-z]+[A-Z][a-z]*", name)
            group = group.group() if group else ""
            if group != prev_group and prev_group:
                lines.append("")
            prev_group = group

            argb = hex_alpha_to_argb(token["value"], token.get("alpha", 1.0))
            comment = f"  // {token['comment']}" if token.get("comment") else ""
            lines.append(f"VISAGE_THEME_COLOR({name}, {format_argb(argb)});{comment}")
        lines.append("")

    # Custom colors
    if theme.get("custom"):
        lines.append("// Project-Specific Colors")
        for name, token in theme["custom"].items():
            if isinstance(token.get("value"), str) and re.match(r"^#", token["value"]):
                argb = hex_alpha_to_argb(token["value"], token.get("alpha", 1.0))
                comment = f"  // {token['comment']}" if token.get("comment") else ""
                lines.append(f"VISAGE_THEME_COLOR({name}, {format_argb(argb)});{comment}")
        lines.append("")

    # Values
    all_values = {}
    all_values.update(theme.get("values", {}))
    # Custom numeric values
    for name, token in theme.get("custom", {}).items():
        if isinstance(token.get("value"), (int, float)):
            all_values[name] = token

    if all_values:
        lines.append("// Values")
        for name, token in all_values.items():
            val = token["value"]
            comment = f"  // {token['comment']}" if token.get("comment") else ""
            lines.append(f"VISAGE_THEME_VALUE({name}, {val}f);{comment}")
        lines.append("")

    lines.append(f"}} // namespace {ns}")
    lines.append("")

    return "\n".join(lines)


def generate_juce_header(theme: dict, source_path: str = "") -> str:
    """Generate a C++ header with a JUCE LookAndFeel class."""
    meta = theme["meta"]
    class_name = re.sub(r"[^A-Za-z0-9]", "", meta["name"]) + "LookAndFeel"

    lines = [
        "#pragma once",
        f"// Generated by Visage Theme Designer",
        f"// JUCE LookAndFeel from: {meta['name']} v{meta.get('version', '1.0.0')}",
        f"// Source: {source_path}" if source_path else "",
        f"// Generated: {datetime.now().isoformat()}",
        "// DO NOT EDIT - regenerate from theme JSON",
        "",
        "#include <juce_gui_basics/juce_gui_basics.h>",
        "",
        f"class {class_name} : public juce::LookAndFeel_V4 {{",
        "public:",
        f"    {class_name}() {{",
    ]

    juce_tokens = theme.get("juce", {})
    for token_name, token in juce_tokens.items():
        # Parse "ClassName::colourIdName" format
        parts = token_name.split("::")
        if len(parts) != 2:
            continue
        class_part, id_part = parts
        argb = hex_alpha_to_argb(token["value"], token.get("alpha", 1.0))
        comment = f"  // {token['comment']}" if token.get("comment") else ""
        lines.append(
            f"        setColour(juce::{class_part}::{id_part}, "
            f"juce::Colour({format_argb(argb)}));{comment}"
        )

    lines.extend([
        "    }",
        "};",
        "",
    ])

    return "\n".join(lines)


def generate_palette_init(theme: dict) -> str:
    """Generate a palette initialization function."""
    meta = theme["meta"]
    ns = re.sub(r"[^a-z0-9_]", "_", meta["name"].lower()).strip("_")

    lines = [
        f"// Generated palette initialization for: {meta['name']}",
        f"// Call after palette.initWithDefaults()",
        f"inline void initThemePalette(visage::Palette& palette) {{",
    ]

    for section in ("colors", "custom"):
        for name, token in theme.get(section, {}).items():
            if not isinstance(token.get("value"), str):
                continue
            if not re.match(r"^#", token["value"]):
                continue
            argb = hex_alpha_to_argb(token["value"], token.get("alpha", 1.0))
            lines.append(f"    palette.setColor({ns}::{name}, visage::Color({format_argb(argb)}));")

    for name, token in theme.get("values", {}).items():
        lines.append(f"    palette.setValue({ns}::{name}, {token['value']}f);")

    lines.extend(["}", ""])
    return "\n".join(lines)


def camel_to_snake(name: str) -> str:
    """Convert camelCase to snake_case."""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def generate_style_system(style_data: dict, source_path: str = "") -> str:
    """Generate C++ code for widget geometry, effects, and typography from a style system JSON."""
    lines = [
        "#pragma once",
        f"// Generated by Visage Theme Designer — Style System",
        f"// Source: {source_path}" if source_path else "",
        f"// Generated: {datetime.now().isoformat()}",
        "// DO NOT EDIT — regenerate from style system JSON",
        "",
        "namespace style {",
        "",
    ]

    geo = style_data.get("geometry", {})
    effects = style_data.get("effects", {})
    typo = style_data.get("typography", {})

    # Global geometry
    g = geo.get("global", {})
    lines.append("// Global geometry")
    for key, val in g.items():
        cpp_name = camel_to_snake(key)
        lines.append(f"constexpr float {cpp_name} = {val}f;")
    lines.append("")

    # Per-widget geometry
    for widget in ["knob", "button", "toggle", "slider", "textInput"]:
        w = geo.get(widget, {})
        if w:
            cpp_widget = widget.lower()
            lines.append(f"// {widget} geometry")
            for key, val in w.items():
                if isinstance(val, (int, float)):
                    cpp_name = f"{cpp_widget}_{camel_to_snake(key)}"
                    lines.append(f"constexpr float {cpp_name} = {val}f;")
                elif isinstance(val, str):
                    cpp_name = f"{cpp_widget}_{camel_to_snake(key)}"
                    lines.append(f'constexpr const char* {cpp_name} = "{val}";')
            lines.append("")

    # Effects
    if effects:
        lines.append("// Effects")
        for effect_name, effect in effects.items():
            if isinstance(effect, dict):
                for key, val in effect.items():
                    cpp_name = f"{effect_name}_{camel_to_snake(key)}"
                    if isinstance(val, bool):
                        lines.append(f"constexpr bool {cpp_name} = {'true' if val else 'false'};")
                    elif isinstance(val, (int, float)):
                        lines.append(f"constexpr float {cpp_name} = {val}f;")
        lines.append("")

    # Typography
    if typo:
        lines.append("// Typography")
        for key, val in typo.items():
            cpp_name = camel_to_snake(key)
            if isinstance(val, (int, float)):
                lines.append(f"constexpr float {cpp_name} = {val}f;")
            elif isinstance(val, str):
                lines.append(f'constexpr const char* {cpp_name} = "{val}";')
        lines.append("")

    lines.append("} // namespace style")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate C++ from Visage theme JSON")
    parser.add_argument("theme_file", help="Path to theme JSON file")
    parser.add_argument("--output", "-o", help="Output file path (stdout if omitted)")
    parser.add_argument(
        "--mode",
        choices=["header", "juce", "both", "palette", "style"],
        default="header",
        help="Output mode (default: header). 'style' generates widget geometry/effects code.",
    )
    parser.add_argument("--namespace", dest="ns", help="C++ namespace (default: derived from theme name)")
    parser.add_argument("--validate-only", action="store_true", help="Validate JSON and exit")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing")
    args = parser.parse_args()

    # Load and validate
    theme = load_theme(args.theme_file)
    errors = validate_theme(theme)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    if args.validate_only:
        print(f"Valid theme: {theme['meta']['name']} ({len(theme.get('colors', {}))} colors, "
              f"{len(theme.get('values', {}))} values, {len(theme.get('custom', {}))} custom, "
              f"{len(theme.get('juce', {}))} JUCE)")
        sys.exit(0)

    source = os.path.relpath(args.theme_file)

    if args.mode == "style":
        # Style mode: read geometry/effects from .stylesystem.json
        style_path = args.theme_file.replace('.json', '.stylesystem.json')
        if not os.path.exists(style_path):
            style_path = args.theme_file  # might be a stylesystem file directly
        try:
            with open(style_path) as f:
                style_data = json.load(f)
            output = generate_style_system(style_data, os.path.relpath(style_path))
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"ERROR: {e}", file=sys.stderr)
            sys.exit(1)
    elif args.mode == "header":
        output = generate_visage_header(theme, source)
    elif args.mode == "juce":
        output = generate_juce_header(theme, source)
    elif args.mode == "palette":
        output = generate_visage_header(theme, source) + "\n" + generate_palette_init(theme)
    elif args.mode == "both":
        visage_out = generate_visage_header(theme, source)
        juce_out = generate_juce_header(theme, source)
        if args.output:
            visage_path = args.output + ".h" if not args.output.endswith(".h") else args.output
            juce_path = visage_path.replace(".h", "LookAndFeel.h")
            if not args.dry_run:
                Path(visage_path).parent.mkdir(parents=True, exist_ok=True)
                with open(visage_path, "w") as f:
                    f.write(visage_out)
                with open(juce_path, "w") as f:
                    f.write(juce_out)
                print(f"Wrote {visage_path}")
                print(f"Wrote {juce_path}")
            else:
                print(f"Would write {visage_path}")
                print(f"Would write {juce_path}")
            sys.exit(0)
        else:
            output = visage_out + "\n// === JUCE LookAndFeel ===\n\n" + juce_out

    if args.output and args.mode != "both":
        if not args.dry_run:
            Path(args.output).parent.mkdir(parents=True, exist_ok=True)
            with open(args.output, "w") as f:
                f.write(output)
            print(f"Wrote {args.output}")
        else:
            print(f"Would write {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
